Repository GodotNuts/GodotFirebase, pull requests merged in 2021-09, with the labels that each got.

#229 Signal added, error handle changed, enum added
  addons/godot-firebase/auth/auth.gd
Labels: enhancement

#231 Update auth.gd
  addons/godot-firebase/auth/auth.gd
Labels: bug, enhancement

#233 add uri prefix to config
  addons/godot-firebase/firebase/firebase.gd
Labels: bug
