Repository GodotNuts/GodotFirebase, pull requests merged in 2021-02, with the labels that each got.

#109 Update templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, priority:0

#112 Create CODE_OF_CONDUCT.md
  .gitattributes
  CODE_OF_CONDUCT.md
Labels: enhancement, priority:0

#119 Auth logout update
  addons/godot-firebase/auth/auth.gd
  addons/godot-firebase/firebase/firebase.gd
  addons/godot-firebase/firestore/firestore.gd
  addons/godot-firebase/storage/storage.gd
Labels: enhancement, priority:1

#115 Dynamic links dev
  addons/godot-firebase/dynamiclinks/dynamiclinks.gd
  addons/godot-firebase/firebase/firebase.gd
  addons/godot-firebase/firebase/firebase.tscn
  override.cfg
  project.godot
Labels: enhancement, priority:0

#120 Inline Class Documentation
  .gitignore
  addons/godot-firebase/auth/auth.gd
  addons/godot-firebase/database/database.gd
  addons/godot-firebase/firebase/firebase.gd
  addons/godot-firebase/firestore/firestore.gd
  addons/godot-firebase/storage/storage.gd
  addons/godot-firebase/storage/storage_reference.gd
  addons/godot-firebase/storage/storage_task.gd
  addons/silicon.util.custom_docs/class_doc_generator.gd
  addons/silicon.util.custom_docs/doc_exporter/doc_exporter.gd
  addons/silicon.util.custom_docs/doc_exporter/editor_help_doc_exporter.gd
  addons/silicon.util.custom_docs/doc_item/argument_doc_item.gd
  addons/silicon.util.custom_docs/doc_item/class_doc_item.gd
  addons/silicon.util.custom_docs/doc_item/constant_doc_item.gd
  addons/silicon.util.custom_docs/doc_item/doc_item.gd
  addons/silicon.util.custom_docs/doc_item/method_doc_item.gd
  addons/silicon.util.custom_docs/doc_item/property_doc_item.gd
  addons/silicon.util.custom_docs/doc_item/signal_doc_item.gd
  addons/silicon.util.custom_docs/plugin.cfg
  addons/silicon.util.custom_docs/plugin.gd
  addons/silicon.util.custom_docs/test_doc_script.gd
  project.godot
Labels: enhancement, priority:0

#140 Fix password change function
  addons/godot-firebase/auth/auth.gd
Labels: bug
